export { createSynth } from './synths.js';
export { createEffectsChain } from './effects.js';
export { ensureAudioContext, startTransport, stopTransport, getTransportTime, getTransportPosition, createSequence } from './transport.js';
export { disposeAll } from './cleanup.js';
export { createAnalyser } from './analyser.js';
export { extractBands, getSimpleBands } from './bands.js';
export { BeatDetector } from './beat-detect.js';
export { EnvelopeFollower } from './envelope.js';
export { createSmoother, createBatchSmoother, applyMapping, easeLinear, easeExponentialIn, easeExponentialOut, easeLogarithmic, easeSineInOut, easeCubicOut, easeQuadraticIn } from './smoothing.js';
export { AudioDataProvider } from './audio-data.js';
export { CompositionManager } from './composition-manager.js';
